### ISSUE TITLE
Another Language - pt_BR

### ISSUE THREAD

**Issue by thimukay** [andrewstech/youtube-for-alexa#5]
Hello Andrew!
Hope you're doing fine!

Awesome, your program works very nicely!
Alexa has now the option to change the language to portuguese from Brazil.
I actually tried to implement in your code another language, I created the InteractionModel_pt.json and I updated the file strings.py with the language I want.
I was just wondering if I have to update something else in the code to make my language works!!

What do you think?

Thank you very much man!

BR,

**Comment by thimukay** [comment]
follow files attached.

[ptBR_lang.zip](https://github.com/andrewstech/youtube-for-alexa/files/3896972/ptBR_lang.zip)

**Comment by andrewstech** [comment]
I am Currently making a new version that should support this

**Comment by andrewstech** [comment]
have a look at this mate https://raw.githubusercontent.com/andrewstech/youtube-for-alexa/master/pt-br-instuctions.txt
