### ISSUE TITLE
ERROR: Unable to download webpage:

### ISSUE THREAD

**Issue by mariannegru** [andrewstech/youtube-for-alexa#6]
Hi,

I'm getting this error:

ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Is there an repo with the code or is just the zip file?

**Comment by andrewstech** [comment]
This is most likely a temporary glitch with Aws. But I will look into this.

**Comment by mariannegru** [comment]
I deleted the function and created it again and works now

**Comment by andrewstech** [comment]
Great I currently developing a new version that's more stable but that
won't be released till early 2020.
