### ISSUE TITLE
Python 2.7 end of life

### ISSUE THREAD

**Issue by mikicho** [andrewstech/youtube-for-alexa#9]
Hey,
Great work!
Python 2.7 end-of-life is 1.1.20, which probably make AWS deprecate this run time, do you plan to convert the lambda code to python 3?

https://stackoverflow.com/questions/57561465/python-2-7-aws-lambda-support-will-end-in-2020

**Comment by andrewstech** [comment]
I am currently developing a new a version to fix this issue and will have
more features hopefully.

**Comment by mikicho** [comment]
Cool, thanks!
